# Generated by Django 4.1 on 2022-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AUD', 'Australian dollar'), ('BRL', 'Brazilian real 2'), ('CAD', 'Canadian dollar'), ('CNY', 'Chinese Renmenbi 3'), ('CZK', 'Czech koruna'), ('DKK', 'Danish krone'), ('EUR', 'Euro'), ('HKD', 'Hong Kong dollar'), ('HUF', 'Hungarian forint 1'), ('ILS', 'Israeli new shekel'), ('JPY', 'Japanese yen 1'), ('MYR', 'Malaysian ringgit 3'), ('MXN', 'Mexican peso'), ('TWD', 'New Taiwan dollar 1'), ('NZD', 'New Zealand dollar'), ('NOK', 'Norwegian krone'), ('PHP', 'Philippine peso'), ('PLN', 'Polish złoty'), ('GBP', 'Pound sterling'), ('RUB', 'Russian ruble'), ('SGD', 'Singapore dollar'), ('SEK', 'Swedish krona'), ('CHF', 'Swiss franc'), ('THB', 'Thai baht'), ('USD', 'United States dollar')], default='', max_length=3, verbose_name='Currency representation')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
