# Generated by Django 4.1 on 2022-09-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_blankmodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blankmodel',
            name='test',
        ),
    ]
