# Generated by Django 4.1 on 2022-09-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_blankmodel_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlankModel',
            new_name='Pay',
        ),
    ]
